name: ${project.artifactId}
description: ${project.description}
version: ${project.version}
api-version: 1.8
author: zPedroo_
main: com.zpedroo.multieconomy.MultiEconomy
depend: [OnlineTime]
softdepend: [Vault, PlaceholderAPI]
load: STARTUP