name: ${project.artifactId}
description: ${project.description}
version: ${project.version}
api-version: 1.16
author: zPedroo_
main: com.zpedroo.multieconomy.MultiEconomy
softdepend: [Vault, PlaceholderAPI]
load: STARTUP