MySQL:
  enabled: false
  host: 'localhost'
  database: 'db'
  username: 'user'
  password: 'pass'
  port: 3306

Settings:
  # A cada quantos segundos todos dados
  # serão salvos na database.
  save-interval: 600
  # Economia que vai ser compatível com o Vault.
  vault-currency: coins
  admin-permission: multieconomy.admin
  permission-message: '&cVocê não possui permissão para executar esse comando!'

Messages:
  buy-all-zero: '&6&lVoltz&f&lMC &8&l➜ &cVocê não pode comprar nenhum item!'
  offline-player: '&6&lVoltz&f&lMC &8&l➜ &cEsse jogador está offline!'
  invalid-amount: '&6&lVoltz&f&lMC &8&l➜ &cO valor inserido é inválido!'
  min-value: '&6&lVoltz&f&lMC &8&l➜ &cA quantia precisa ser acima de {tax}!'
  insufficient-stock: '&6&lVoltz&f&lMC &8&l➜ &cEsse item não possui estoque!'
  insufficient-currency: '&6&lVoltz&f&lMC &8&l➜ &cVocê não possui essa quantia! ({has}/{need})'
  insufficient-level: '&6&lVoltz&f&lMC &8&l➜ &cVocê não possui nível suficiente! ({has}/{need})'
  need-space: '&6&lVoltz&f&lMC &8&l➜ &cVocê não possui espaço suficiente no seu inventário! ({has}/{need})'
  send-to-yourself: '&6&lVoltz&f&lMC &8&l➜ &cVocê não pode enviar {currency_name} para si mesmo!'
  top-one-display: '&6&lVoltz&f&lMC &8&l➜ &7Jogador mais rico: {tag} &f{player} &7com uma riqueza de {amount_display}&7!'
  sent:
    - ''
    - '&6&lVoltz&f&lMC &8&l➜ &7Transação efetuada com sucesso! Confira abaixo as informações:'
    - ''
    - ' &8▶ &7Moeda: {currency_display}'
    - ' &8▶ &7Enviado para: &f{target}'
    - ' &8▶ &7Saldo enviado: {amount_display}'
    - ' &8▶ &7Saldo recebido: {received_display} &7(&f-{tax}%&7)'
    - ' &8▶ &7ID: &f#{id}'
    - ''

  received:
    - ''
    - '&6&lVoltz&f&lMC &8&l➜ &7Uma nova transação foi efetuada! Confira abaixo as informações:'
    - ''
    - ' &8▶ &7Moeda: {currency_display}'
    - ' &8▶ &7Feita por: &f{actor}'
    - ' &8▶ &7Saldo recebido: &f{received}'
    - ' &8▶ &7ID: &f#{id}'
    - ''

  withdraw:
    - '&6&lVoltz&f&lMC &8&l➜ &7Digite no chat quanto deseja retirar!'
    - '&6&lVoltz&f&lMC &8&l➜ &7Lembre-se que há uma taxa de &f{tax}%&7!'

  choose-amount:
    - ''
    - '&6&lVoltz&f&lMC &8&l➜ &7Digite no chat quantos itens deseja comprar!'
    - '&6&lVoltz&f&lMC &8&l➜ &7Para comprar o máximo possível digite ''&f*&7''!'
    - ''
    - ' &8▶ &7Comprando: &f{item}'
    - ' &8▶ &7Preço: {price}'
    - ''
  successful-purchased:
    - ''
    - '&6&lVoltz&f&lMC &8&l➜ &7Compra efetuada com sucesso!'
    - ''
    - ' &8▶ &7Item adquirido: &f{item}'
    - ' &8▶ &7Quantia: &fx{amount}'
    - ' &8▶ &7Preço: {price}'
    - ''

  confirm:
    - ''
    - '&6&lVoltz&f&lMC &8&l➜ &7Digite o comando novamente para confirmar a transação!'
    - ''
    - ' &8▶ &7Moeda: {currency_display}'
    - ' &8▶ &7Enviando para: &f{target}'
    - ' &8▶ &7Saldo a ser enviado: {amount_display}'
    - ' &8▶ &7Saldo a ser recebido: {received_display} &7(&f-{tax}%&7)'
    - ''

  new-top-one:
    - ''
    - '&6&lVoltz&f&lMC &8&l➜ &7O jogador &f{player} &7é o novo {tag} &7com uma riqueza de {amount_display}&7!'
    - ''

Next-Page:
  type: ARROW
  name: '&aPróxima Página'
  slot: 26

Previous-Page:
  type: ARROW
  name: '&cPágina Anterior'
  slot: 18

Time-Formatter:
  second: '&7segundo&f'
  seconds: '&7segundos&f'
  minute: '&7minuto&f'
  minutes: '&7minutos&f'
  hour: '&7hora&f'
  hours: '&7horas&f'
  day: '&7dia&f'
  days: '&7dias&f'
  now: '&fAgora'

Number-Formatter:
  - "k"
  - "M"
  - "B"
  - "T"
  - "Q"
  - "QQ"
  - "S"
  - "SS"
  - "O"
  - "N"
  - "D"